### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by rvansa** [thumbsup/thumbsup#132] opened 2018-09-03 20:51 UTC
## Bug report

If running as an npm package:

```
Thumbsup version: 2.4.2
Node version: v8.11.4
NPM version: 5.6.0
Operating system: Linux 4.17.19-200.fc28.armv7hl #1 SMP Fri Aug 24 17:23:29 UTC 2018 armv7l armv7l armv7l GNU/Linux
```

I have installed thumbsup using `npm install -g thumbsup` as root user since I had permissions problems. In the end I got the install succesful, however when trying to run it I get

```
/usr/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/compiled/8.11.4/linux/arm/better_sqlite3.node
    at bindings (/usr/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/database.js:4:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/index.js:2:18)
```

I've followed suggestions to try installing with `--unsafe-perm` as some comments in https://github.com/nodejs/node-gyp/issues/454 suggest (despite others having security concerns), but to no avail. To be on the safe side I've `chown`ed and `chgrp`ed everything to root to be on the safe side but it didn't help. The tried folders really don't exist:

```
$ ll /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3
total 48
drwxr-xr-x. 3 root root 4096 Sep  2 22:35 benchmark
-rw-r--r--. 1 root root  670 Aug 24  2017 binding.gyp
drwxr-xr-x. 2 root root 4096 Sep  2 22:35 deps
-rw-r--r--. 1 root root  163 Jun  6  2017 index.js
drwxr-xr-x. 2 root root 4096 Sep  2 22:35 lib
-rw-r--r--. 1 root root 1077 Mar  1  2017 LICENSE
-rw-r--r--. 1 root root 2253 Sep  2 22:36 package.json
-rw-r--r--. 1 root root 3084 Jan 20  2018 README.md
drwxr-xr-x. 5 root root 4096 Sep  2 22:35 src
drwxr-xr-x. 2 root root 4096 Sep  2 22:35 test
-rw-r--r--. 1 root root 2143 Sep 10  2016 TIPS.md
-rw-r--r--. 1 root root 3558 Aug 28  2017 TODO
```

Suggestions please?

**Comment by rprieto** [comment] 2019-02-17 08:56
Hi, sorry I couldn't reproduce this. Did you have any luck on your end?

In April I will update to the latest version of `better-sqlite3` which might fix the issue. It does support Node v6 so I wanted to wait until it goes out of LTS. If that doesn't work it might be worth raising an issue on the [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) repo.

**Comment by rprieto** [comment] 2019-02-17 09:06
Have a look at #112 as well that mentions a solution around installation binding problems.

**Comment by rprieto** [comment] 2019-06-11 18:28
Hi, `sqlite` has been upgraded to the latest version. I'll close this issue as it should be fixed now, but please leave a comment if you still have problems and I will re-open it.

**Closed by rprieto** 2019-06-11 18:28 UTC
Labels: troubleshooting
