### ISSUE TITLE
2.0.0 -Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ReSearchITEng** [thumbsup/thumbsup#62] opened 2017-04-01 15:08 UTC
docker run -t                -v /etc/localtime:/etc/localtime   -v `pwd`:/work             -u $(id -u):$(id -g)       thumbsup:2.x.x thumbsup --input /work/media --output /work/gallery --sort-albums-by title --original-photos true

Finding media       [=========================] 2/2 done
Updating database   [-------------------------] 0/2 /usr/lib/node_modules/thumbsup/src/index.js:30
        fileCollection = dbFiles.map(f => new File(f, opts))
                                ^

TypeError: Cannot read property 'map' of undefined
    at EventEmitter.database.update (/usr/lib/node_modules/thumbsup/src/index.js:30:33)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at exiftool.read (/usr/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/files.js:62:33)
    at ChildProcess.child.on (/usr/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/exiftool.js:52:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by rprieto** [comment] 2017-04-02 01:45
Hi, thanks for the report. 

- did you build the Docker image yourself? Unfortunately the docs are ahead of reality, and the image hasn't been pushed yet
- is it systematic? I'll see if I can reproduce the issue

**Comment by rprieto** [comment] 2017-05-22 12:08
Hi, closing for now but feel free to re-open if you have more detail.

**Closed by rprieto** 2017-05-22 12:08 UTC

**Comment by rprieto** [comment] 2017-05-24 07:51
@ReSearchITEng I finally reproduced this, sorry for the delay. It happens when upgrading from thumbsup v1 to v2, since the `metadata.json` format changed. There was a bug that prevented the following error message from showing:

> If migrating from thumbsup v1, delete <metadata.json> to rebuild the database from scratch

This is now fixed on `master`.
