### ISSUE TITLE
configurable timeout for slideshows

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#129] opened 2018-08-23 15:07 UTC
## Feature request

In slideshow mode, the timeout before switching to the next photo is not configurable, it's something like 3 seconds.

This timeout should be configurable on the admin side (somewhere on the json config file) but also on the viewer side, with a small way to set this default timeout (never, 1, 3, 5, 10 seconds are good default values).

**Comment by rprieto** [comment] 2018-08-23 16:00
I think this is a duplicate of #116 and #119. Let me know otherwise.

**Closed by rprieto** 2018-08-23 16:00 UTC
