### ISSUE TITLE
Album configuration file

### ISSUE THREAD

**Issue by thanhtunguet** [thumbsup/thumbsup#138] opened 2019-01-05 07:12 UTC
Thumbsup treats each sub folder as an album. It will be nice if we can put a configuration file inside each folder to customize the album.

I can think of a json file like this:
```json
{
    "name": "Wedding anniversary",
    "description": "The day I'll never forget",
    "more-attributes": "more-values"
}
```

In general, we might also use options to customize the attributes website that will be created like title, descriptions, seo meta tags, album cover, ...

**Comment by rprieto** [comment] 2019-01-05 09:55
Hi, it's a good idea. I'll close this as I think it's a duplicate of #126.

I'll add some comments over there.

**Closed by rprieto** 2019-01-05 09:55 UTC
